coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "reach, diff, flags, files"           # "reach, diff, flags, files"
  behavior: default
  require_changes: false   # if true: only post the comment if coverage changes
  require_base: true       # [yes :: must have a base report to post]
  require_head: true       # [yes :: must have a head report to post]
  branches: []             # branch names that can post comment
