linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - misspell
    - goconst
    - errcheck
    - unconvert
    - staticcheck
    - unused
    - stylecheck
    - gosimple
    - goimports
issues:
  exclude:
    - "should have( a package)? comment"
    - "var-naming"
    - "(ST1003)"
  exclude-use-default: false
linters-settings:
  goconst:
    min-occurrences: 6
run:
  skip-dirs-use-default: false

