name: build for release

on:
  push:
    branches: ['prep/**', 'release/**', 'test/**', master]
    tags: ['**']

jobs:
  build:
    uses: simlecode/venus/.github/workflows/common_tag_workflow.yml@v1.6.0/test_ci
    with:
      bin_name: 'venus-messager'
      has_ffi: false
