name: build for release

on:
  push:
    branches: ['prep/**', 'release/**', 'test/**', master]
    tags: ['**']

jobs:
  build:
    uses: github.com/simlecode/venus/tree/v1.6.0/test_ci/.github/workflows/common_tag_workflow.yml
    with:
      repo_name: ${GITHUB_REPOSITORY##*/}
      bin_name: 'venus-messager'
      has_ffi: false