name: Docker Image CI

on:
  push:
    branches: ['prep/**', 'release/**', 'test/**', master]
    tags: ['**']
  pull_request:
    branches:
      - '**'

jobs:

  build_docker_image:
    uses: simlecode/venus/.github/workflows/common_docker_image.yml@v1.6.0/test_ci
