name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Deps
      env:
        GOPROXY: "https://proxy.golang.org,direct"
        GO111MODULE: "on"
      run: |
        go mod download

    - name: Build
      env:
        GOPROXY: "https://proxy.golang.org,direct"
        GO111MODULE: "on"
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
