name: Go

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./.codecov.yml # optional
        flags: unittests # optional
        verbose: true # optional (default = false)