name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOPROXY: https://goproxy.cn

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Deps
      run: git submodule sync && git submodule update --init && ./extern/filecoin-ffi/install-filcrypto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
